AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Go sample template

Globals:
  Function:
    Timeout: 5

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: build/
      Handler: hello-world
      Runtime: go1.x
      Tracing: Active 
      Events:
        HelloEvent:
          Type: Api 
          Properties:
            Path: /hello
            Method: GET
            RestApiId: !Ref MyApi
      Environment: 
        Variables:
          EXTRA: "Ready to Go"

Outputs:
  HelloWorldAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/v1/hello/"
  HelloWorldFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
